from keras.models import load_model
from keras.utils.vis_utils import plot_model

model1 = load_model(('Model - 1/model1'))
model2 = load_model(('Model - 2/model2'))
model3 = load_model(('Model - 3/model3'))
model3_1 = load_model(('Model - 3.1/model3.1'))
model3_2 = load_model(('Model - 3.2/model3.2'))
model3_2_1 = load_model(('Model - 3.2.1/model3.2.1'))
model3_2_2 = load_model(('Model - 3.2.2/model3.2.2'))
model3_2_2_0_1 = load_model(('Model - 3.2.2.0.1/model3.2.2.0.1'))
model3_2_2_0_2 = load_model(('Model - 3.2.2.0.2/model3.2.2.0.2'))
model3_2_2_1 = load_model(('Model - 3.2.2.1/model3.2.2.1'))
model3_2_2_2 = load_model(('Model - 3.2.2.2/model3.2.2.2'))
model3_2_2_3 = load_model(('Model - 3.2.2.3/model3.2.2.3'))
model3_2_2_4 = load_model(('Model - 3.2.2.4/model3.2.2.4'))
model3_2_3 = load_model(('Model - 3.2.3/model3.2.3'))
model3_2_4 = load_model(('Model - 3.2.4/model3.2.4'))

tmodel1 = load_model(('Transfer Model - 1/tf_model1'))
tmodel2 = load_model(('Transfer Model - 2/tf_model2'))
tmodel3 = load_model(('Transfer Model - 3/tf_model3'))

plot_model(model1, to_file='Model - 1/model1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model2, to_file='Model - 2/model2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3, to_file='Model - 3/model3_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_1, to_file='Model - 3.1/model3_1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2, to_file='Model - 3.2/model3_2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_1, to_file='Model - 3.2.1/model3_2_1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2, to_file='Model - 3.2.2/model3_2_2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_0_1, to_file='Model - 3.2.2.0.1/model3_2_2_0_1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_0_2, to_file='Model - 3.2.2.0.2/model3_2_2_0_2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_1, to_file='Model - 3.2.2.1/model3_2_2_1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_2, to_file='Model - 3.2.2.2/model3_2_2_2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_3, to_file='Model - 3.2.2.3/model3_2_2_3_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_2_4, to_file='Model - 3.2.2.4/model3_2_2_4_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_3, to_file='Model - 3.2.3/model3_2_3_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(model3_2_4, to_file='Model - 3.2.4/model3_2_4_architecture.png', show_shapes=True, show_layer_names=True)

plot_model(tmodel1, to_file='Transfer Model - 1/tmodel1_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(tmodel2, to_file='Transfer Model - 2/tmodel2_architecture.png', show_shapes=True, show_layer_names=True)
plot_model(tmodel3, to_file='Transfer Model - 3/tmodel3_architecture.png', show_shapes=True, show_layer_names=True)
